version: "3.8"

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./app
      args:
        VITE_API_BASE_URL: http://backend:5000/api/v1
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
